# Generated by Django 6.0.2 on 2026-07-10 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File_uplaoding',
            new_name='File_uploading',
        ),
    ]
